---
- name: Verify
  hosts: all
  gather_facts: false
  vars:
    ansible_connection: winrm
    ansible_port: 5986
    ansible_user: "{{ lookup('ansible.builtin.env', 'INSTANCE_TESTHOST_USERID')}}"
    ansible_password: "{{ lookup('ansible.builtin.env', 'INSTANCE_TESTHOST_PASSWORD')}}"
    ansible_winrm_server_cert_validation: ignore
  
  tasks:
    - gocallag.hyperv.disk:   
        path: 'c:\temp\test.vhd'
        size: 10
        state: present
      register: info
    - debug: msg="{{ info }}"
    - gocallag.hyperv.disk:   
        path: 'c:\temp\test.vhd'
        state: absent
      register: info
    - debug: msg="{{ info }}"

