---
- name: Converge
  hosts: all
  vars:
    ansible_connection: winrm
    ansible_port: 5986
    ansible_user: "{{ lookup('ansible.builtin.env', 'INSTANCE_TESTHOST_USERID')}}"
    ansible_password: "{{ lookup('ansible.builtin.env', 'INSTANCE_TESTHOST_PASSWORD')}}"
    ansible_winrm_server_cert_validation: ignore
  
  tasks:
    - name: Get information about VM
      gocallag.hyperv.vm_info:
        names:
         - LAB-Test
      register: info
    - debug: msg="{{ info }}"

    - name: Collect information about a specific VM, 2nd in list
      gocallag.hyperv.vm_info:
        id: '{{ info.output.value[1].Id }}'
      register: myvm
    - debug: msg="{{ myvm }}"

    - name: Get information about VM
      gocallag.hyperv.vm_info:
        power_state: 'Running'
      register: info
    - debug: msg="{{ info }}"

    - name: Collect information about a specific VM, 1st in list
      gocallag.hyperv.vm_info:
        id: '{{ info.output.value[0].Id }}'
      register: myvm
    - debug: msg="{{ myvm }}"