---
- name: Cleanup
  hosts: all
  gather_facts: false
  vars:
    ansible_connection: winrm
    ansible_port: 5986
    ansible_user: "{{ lookup('ansible.builtin.env', 'INSTANCE_TESTHOST_USERID')}}"
    ansible_password: "{{ lookup('ansible.builtin.env', 'INSTANCE_TESTHOST_PASSWORD')}}"
    ansible_winrm_server_cert_validation: ignore
  
  tasks:
    - name: Delete test VM  # Note: this will delete ALL VM's called LAB-Test, including powered-on VM's
      gocallag.hyperv.vm:
        name: LAB-Test
        state: absent
      register: output
    - name: Delete test VM - G2
      gocallag.hyperv.vm:
        name: LAB-Test-G2
        state: absent
      register: output
