---
- name: Cleanup
  hosts: all
  gather_facts: false
  vars:
    ansible_connection: winrm
    ansible_port: 5986
    ansible_user: "{{ lookup('ansible.builtin.env', 'INSTANCE_TESTHOST_USERID')}}"
    ansible_password: "{{ lookup('ansible.builtin.env', 'INSTANCE_TESTHOST_PASSWORD')}}"
    ansible_winrm_server_cert_validation: ignore
  
  tasks:
    - name: Delete VM
      gocallag.hyperv.vm:  # this will delete all VM's called LAB-Test, there can be multiple in Hyper-V
        name: LAB-Test
        state: absent
      register: output
